//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposalSFG
    {
        public string ID { get; set; }
        public string ReceivingID { get; set; }
        public string SemiFinishGoodID { get; set; }
        public string Barcode { get; set; }
        public string LotNo { get; set; }
        public decimal DisposeQty { get; set; }
        public string DisposeMethod { get; set; }
        public System.DateTime DisposedOn { get; set; }
        public string DisposedBy { get; set; }
    }
}
