//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishGood
    {
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string Specifications { get; set; }
        public string StockCode { get; set; }
        public string StockCategoryCode { get; set; }
        public string StockCategoryName { get; set; }
        public Nullable<int> InputTaxRate { get; set; }
        public Nullable<int> OutputTaxRate { get; set; }
        public Nullable<System.DateTime> EnabledDate { get; set; }
        public string ABLIAN { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> WeightPerBag { get; set; }
        public Nullable<decimal> SpecificGravity { get; set; }
        public Nullable<decimal> PerPalletWeight { get; set; }
        public string UoM { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
