//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InboundReceive()
        {
            this.InboundPutaways = new HashSet<InboundPutaway>();
        }
    
        public string ID { get; set; }
        public string InboundOrderID { get; set; }
        public string StockCode { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public int LastSeries { get; set; }
    
        public virtual InboundOrder InboundOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundPutaway> InboundPutaways { get; set; }
    }
}
