//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public string ID { get; set; }
        public string ReceivingDetailID { get; set; }
        public decimal InspectionQty { get; set; }
        public string InspectionMethod { get; set; }
        public System.DateTime InspectedOn { get; set; }
        public string InspectedBy { get; set; }
        public int LastSeries { get; set; }
    
        public virtual ReceivingDetail ReceivingDetail { get; set; }
    }
}
