//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueSlipReturn
    {
        public string ID { get; set; }
        public string IssueSlipOrderID { get; set; }
        public string PrevStockCode { get; set; }
        public string StockCode { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public decimal QtyPerBag { get; set; }
        public decimal ReturnQty { get; set; }
        public string ReturnMethod { get; set; }
        public string ReturnedBy { get; set; }
        public System.DateTime ReturnedOn { get; set; }
        public int LastSeries { get; set; }
    
        public virtual IssueSlipOrder IssueSlipOrder { get; set; }
    }
}
