//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JudgementSFG
    {
        public string ID { get; set; }
        public string ReceivingID { get; set; }
        public decimal JudgementQty { get; set; }
        public string JudgementMethod { get; set; }
        public System.DateTime JudgeOn { get; set; }
        public string JudgeBy { get; set; }
    }
}
