//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualStock
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Lot { get; set; }
        public decimal BagQty { get; set; }
        public decimal FullBagQty { get; set; }
        public decimal FullQty { get; set; }
        public decimal RemainQty { get; set; }
        public decimal TotalQty { get; set; }
        public string UoM { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public int Seq { get; set; }
    }
}
