//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.MenuControls = new HashSet<MenuControl>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string Index { get; set; }
        public string Path { get; set; }
        public string Icon { get; set; }
        public string ParentID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuControl> MenuControls { get; set; }
    }
}
