//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string StockCode { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string PrevBinRackID { get; set; }
        public string PrevBinRackCode { get; set; }
        public string PrevBinRackName { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> QtyPerBag { get; set; }
        public string NewBinRackID { get; set; }
        public string NewBinRackCode { get; set; }
        public string NewBinRackName { get; set; }
        public string TransactionStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
