//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRBoxApproval
    {
        public System.Guid ID { get; set; }
        public string PRBoxGroupCode { get; set; }
        public string PRBoxGroupDescription { get; set; }
        public int SequenceNo { get; set; }
        public string PRBoxName { get; set; }
        public string PRBoxTitle { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
