//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPlanHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionPlanHeader()
        {
            this.ProductionPlanDetails = new HashSet<ProductionPlanDetail>();
            this.ProductionPlanOrders = new HashSet<ProductionPlanOrder>();
        }
    
        public string ID { get; set; }
        public string Code { get; set; }
        public int LineNumber { get; set; }
        public string OrderNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string RecipeNumber { get; set; }
        public int BatchQty { get; set; }
        public decimal TotalQty { get; set; }
        public System.DateTime ETA { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan FinishTime { get; set; }
        public string Remarks { get; set; }
        public string TransactionStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FinishedBy { get; set; }
        public Nullable<System.DateTime> FinishedOn { get; set; }
    
        public virtual Formula Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionPlanDetail> ProductionPlanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionPlanOrder> ProductionPlanOrders { get; set; }
    }
}
