//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPlanOrder
    {
        public string ID { get; set; }
        public string HeaderID { get; set; }
        public string PRFID { get; set; }
        public System.DateTime ETA { get; set; }
        public string OrderNumber { get; set; }
        public decimal OrderQty { get; set; }
        public int BatchQty { get; set; }
        public decimal TotalQty { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ProductionPlanHeader ProductionPlanHeader { get; set; }
    }
}
