//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionRequestDetail
    {
        public string ID { get; set; }
        public string HeaderID { get; set; }
        public string OrderNumber { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public decimal Qty { get; set; }
        public string UoM { get; set; }
        public System.DateTime ETA { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductionRequestHeader ProductionRequestHeader { get; set; }
    }
}
