//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Putaway
    {
        public string ID { get; set; }
        public string ReceivingDetailID { get; set; }
        public decimal PutawayQty { get; set; }
        public string PutawayMethod { get; set; }
        public string BinRackID { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public System.DateTime PutOn { get; set; }
        public string PutBy { get; set; }
    
        public virtual ReceivingDetail ReceivingDetail { get; set; }
    }
}
