//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCReturn
    {
        public string ID { get; set; }
        public string QCPutawayID { get; set; }
        public string StockCode { get; set; }
        public string NewStockCode { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public System.DateTime NewExpDate { get; set; }
        public string PrevBinRackID { get; set; }
        public string PrevBinRackCode { get; set; }
        public string PrevBinRackName { get; set; }
        public string BinRackID { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public decimal PutawayQty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string PutawayMethod { get; set; }
        public System.DateTime PutOn { get; set; }
        public string PutBy { get; set; }
    
        public virtual QCPutaway QCPutaway { get; set; }
    }
}
