//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingSFG
    {
        public string ID { get; set; }
        public string PurchaseRequestID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string UoM { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual PurchaseRequestDetail PurchaseRequestDetail { get; set; }
    }
}
