//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receiving()
        {
            this.ReceivingDetails = new HashSet<ReceivingDetail>();
        }
    
        public string ID { get; set; }
        public string PurchaseRequestID { get; set; }
        public string RefNumber { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string UoM { get; set; }
        public System.DateTime ETA { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual PurchaseRequestDetail PurchaseRequestDetail { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingDetail> ReceivingDetails { get; set; }
    }
}
