//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceivingDetail()
        {
            this.Inspections = new HashSet<Inspection>();
            this.Judgements = new HashSet<Judgement>();
            this.Putaways = new HashSet<Putaway>();
        }
    
        public string ID { get; set; }
        public string HeaderID { get; set; }
        public string StockCode { get; set; }
        public string DoNo { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public decimal Qty { get; set; }
        public decimal NGQty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string UoM { get; set; }
        public System.DateTime ATA { get; set; }
        public string Remarks { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public bool COA { get; set; }
        public int LastSeries { get; set; }
        public string FotoCOA { get; set; }
        public Nullable<int> LastFotoCOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Judgement> Judgements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Putaway> Putaways { get; set; }
        public virtual Receiving Receiving { get; set; }
    }
}
