//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemiFinishGood
    {
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string StockCategoryName { get; set; }
        public string CustProdName { get; set; }
        public string ExpiredDate { get; set; }
        public string AB { get; set; }
        public decimal WeightPerBag { get; set; }
        public decimal PerPalletWeight { get; set; }
        public string UoM { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
