//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSFG
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal QtyPerBag { get; set; }
        public string BinRackID { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public System.DateTime ReceivedAt { get; set; }
        public bool OnInspect { get; set; }
    
        public virtual BinRack BinRack { get; set; }
    }
}
