//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transfer()
        {
            this.TransferDetails = new HashSet<TransferDetail>();
        }
    
        public System.Guid ID { get; set; }
        public string TransferNo { get; set; }
        public string ProductID { get; set; }
        public string ProductType { get; set; }
        public string ProductIDTarget { get; set; }
        public string ProductTypeTarget { get; set; }
        public decimal QtyTotal { get; set; }
        public decimal QtyTransfer { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferDetail> TransferDetails { get; set; }
    }
}
