//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransformDetail
    {
        public string ID { get; set; }
        public string TransformID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string StockCode { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string TransformMethod { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public Nullable<System.DateTime> PrintedAt { get; set; }
        public string PrintedBy { get; set; }
        public int LastSeries { get; set; }
    
        public virtual Transform Transform { get; set; }
    }
}
