//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid TransferID { get; set; }
        public string StockIDSource { get; set; }
        public decimal Qty { get; set; }
        public string ProductIDSource { get; set; }
        public string ProductIDTarget { get; set; }
        public string StockIDTarget { get; set; }
        public decimal QtyTransfer { get; set; }
        public string StockIDSourceRetail { get; set; }
        public decimal QtyRetail { get; set; }
        public string StockIDTargetRetail { get; set; }
        public decimal QtyTransferRetail { get; set; }
    
        public virtual Transfer Transfer { get; set; }
    }
}
