//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Username { get; set; }
        public string FullName { get; set; }
        public string Photo { get; set; }
        public string Password { get; set; }
        public string RoleID { get; set; }
        public bool IsActive { get; set; }
        public string Token { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string AreaType { get; set; }
        public bool MobileUser { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
