//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBinRackItem
    {
        public string BinRackAreaCode { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
