//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInbound2
    {
        public string DocumentNo { get; set; }
        public string WHName { get; set; }
        public string RMCode { get; set; }
        public string RMName { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> Bag { get; set; }
        public decimal FullBag { get; set; }
        public decimal Total { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<decimal> QtyPutaway { get; set; }
        public string PutawayBy { get; set; }
        public Nullable<System.DateTime> PutawayOn { get; set; }
        public string BinRack { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
        public string ID { get; set; }
    }
}
