//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIssueSlipListTransaction
    {
        public string RMCode { get; set; }
        public string RMName { get; set; }
        public string WHName { get; set; }
        public string InOut { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<decimal> InQty { get; set; }
        public Nullable<decimal> OutQty { get; set; }
        public Nullable<decimal> InventoryQty { get; set; }
        public string InOutType { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
    }
}
