//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vIssueSlipReport
    {
        public string ID_Order { get; set; }
        public string ID_Header { get; set; }
        public string Header_Code { get; set; }
        public string Header_Name { get; set; }
        public Nullable<System.DateTime> Header_ProductionDate { get; set; }
        public string RM_Code { get; set; }
        public string RM_Name { get; set; }
        public string RM_VendorName { get; set; }
        public decimal Wt_Request { get; set; }
        public decimal SupplyQty { get; set; }
        public string FromBinRackCode { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string PickedBy { get; set; }
        public decimal ReturnQty { get; set; }
        public string ToBinRackCode { get; set; }
        public string PutBy { get; set; }
    }
}
