//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListBarcodeSFG
    {
        public string StockCode { get; set; }
        public string ProductCode { get; set; }
        public string MaterialName { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string UoM { get; set; }
        public decimal QtyPerBag { get; set; }
    }
}
