//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMovement
    {
        public string WHName { get; set; }
        public string RMCode { get; set; }
        public string RMName { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> OriginBag { get; set; }
        public Nullable<decimal> OriginFullBag { get; set; }
        public Nullable<decimal> OriginTotal { get; set; }
        public string OriginBinRack { get; set; }
        public string PutawayBy { get; set; }
        public Nullable<System.DateTime> PutawayOn { get; set; }
        public Nullable<decimal> DestinationBag { get; set; }
        public Nullable<decimal> DestinationFullBag { get; set; }
        public Nullable<decimal> DestinationTotal { get; set; }
        public string DestinationBinRack { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
    }
}
