//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vQCInspectExpired2
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string MaterialType { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> ExpirationDay { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<System.DateTime> NewExpDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<bool> Priority { get; set; }
        public string InspectionStatus { get; set; }
        public string InspectedBy { get; set; }
        public Nullable<System.DateTime> InspectedOn { get; set; }
    }
}
