//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vQCInspection
    {
        public string DocumentNo { get; set; }
        public string WHName { get; set; }
        public string RMCode { get; set; }
        public string RMName { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string LotNo { get; set; }
        public Nullable<decimal> Bag { get; set; }
        public decimal FullBag { get; set; }
        public decimal Total { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<decimal> PickingBag { get; set; }
        public decimal PickingFullBag { get; set; }
        public decimal PickingTotal { get; set; }
        public string PickingBinRack { get; set; }
        public string PickingBy { get; set; }
        public Nullable<System.DateTime> PickingOn { get; set; }
        public Nullable<int> ActionExtendDuration { get; set; }
        public Nullable<System.DateTime> ActionExpDate { get; set; }
        public string ActionDispose { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveOn { get; set; }
        public string PrintLabelBy { get; set; }
        public System.DateTime PrintLabelOn { get; set; }
        public Nullable<decimal> PutawayBag { get; set; }
        public decimal PutawayFullBag { get; set; }
        public decimal PutawayTotal { get; set; }
        public string PutawayBinRack { get; set; }
        public string PutawayBy { get; set; }
        public System.DateTime PutawayOn { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
    }
}
