//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRawMaterialConvert
    {
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public decimal Qty { get; set; }
        public string UoM { get; set; }
        public string ShelfLife { get; set; }
        public decimal MinPurchaseQty { get; set; }
        public string Maker { get; set; }
        public string Vendor { get; set; }
        public decimal PoRate { get; set; }
        public string ManfCd { get; set; }
        public string VendorCode { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsConvertible { get; set; }
        public Nullable<decimal> MinPurchaseQtyLitre { get; set; }
    }
}
