//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceivingSFG2
    {
        public string PurchaseRequestID { get; set; }
        public string Code { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string UoM { get; set; }
        public decimal QtyPerBag { get; set; }
        public Nullable<decimal> TotalOrder { get; set; }
        public Nullable<decimal> AvailableReceive { get; set; }
        public Nullable<decimal> TotalReceive { get; set; }
    }
}
