//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceivingReport2
    {
        public string DestinationName { get; set; }
        public string RefNumber { get; set; }
        public string SourceName { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string LotNo { get; set; }
        public decimal PerBag { get; set; }
        public Nullable<decimal> FullBag { get; set; }
        public decimal Total { get; set; }
        public string Area { get; set; }
        public string RackNo { get; set; }
        public string DoNo { get; set; }
        public string TransactionStatus { get; set; }
        public string SourceCode { get; set; }
        public string SourceType { get; set; }
        public System.DateTime ATA { get; set; }
    }
}
