//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceivingSFG_notused
    {
        public string ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Barcode { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPerBag { get; set; }
        public Nullable<decimal> NGQty { get; set; }
        public string UoM { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> JudgementQty { get; set; }
        public string JudgementMethod { get; set; }
        public string JudgeBy { get; set; }
        public Nullable<System.DateTime> JudgeOn { get; set; }
        public Nullable<decimal> PutawayQty { get; set; }
        public string BinRackID { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public string PutawayMethod { get; set; }
        public string PutBy { get; set; }
        public Nullable<System.DateTime> PutOn { get; set; }
        public Nullable<decimal> DisposeQty { get; set; }
        public string DisposeMethod { get; set; }
        public string DisposedBy { get; set; }
        public Nullable<System.DateTime> DisposedOn { get; set; }
    }
}
