//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceivingSFGDataTable_notused
    {
        public string ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string LotNo { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyPerBag { get; set; }
        public string UoM { get; set; }
        public decimal QtyActualReceiving { get; set; }
        public decimal QtyBagReceiving { get; set; }
        public decimal QtyPerBagReceiving { get; set; }
        public decimal QtyBagRetail { get; set; }
        public decimal NGQty { get; set; }
        public decimal JudgementQty { get; set; }
        public Nullable<decimal> JudgementQtyBagRetail { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
    }
}
