//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceivingReport5
    {
        public string ID { get; set; }
        public string DestinationName { get; set; }
        public string SourceCode { get; set; }
        public string SourceType { get; set; }
        public string PONo { get; set; }
        public string Supplier { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<System.DateTime> Schedule { get; set; }
        public string TotalQtyPo { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string LotNo { get; set; }
        public string QtyPerBag { get; set; }
        public string QtyBag { get; set; }
        public string Total { get; set; }
        public string DoNo { get; set; }
        public string Ok { get; set; }
        public string NgDamage { get; set; }
        public string NgWet { get; set; }
        public string NgContamination { get; set; }
        public string COA { get; set; }
        public string StatusPo { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string QtyPutaway { get; set; }
        public string PutawayBy { get; set; }
        public System.DateTime PutawayOn { get; set; }
        public string Area { get; set; }
        public string RackNo { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
