//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReceivingOld_notused
    {
        public string ID { get; set; }
        public string PurchaseRequestID { get; set; }
        public string RefNumber { get; set; }
        public string RawMaterialID { get; set; }
        public string RawMaterialCode { get; set; }
        public string RawMaterialName { get; set; }
        public string Barcode { get; set; }
        public string DONo { get; set; }
        public string LotNo { get; set; }
        public Nullable<bool> COA { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public Nullable<decimal> OKQty { get; set; }
        public Nullable<decimal> NGQty { get; set; }
        public string UoM { get; set; }
        public System.DateTime ETA { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public Nullable<decimal> InspectionQty { get; set; }
        public string InspectedBy { get; set; }
        public Nullable<System.DateTime> InspectedOn { get; set; }
        public string InspectionMethod { get; set; }
        public string NGBinRackID { get; set; }
        public string NGBinRackCode { get; set; }
        public string NGBinRackName { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> ConvertedQty { get; set; }
        public string ConvertedUoM { get; set; }
        public string SourceType { get; set; }
        public string SourceID { get; set; }
        public string SourceCode { get; set; }
        public string SourceName { get; set; }
        public string SourceAddress { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseType { get; set; }
        public Nullable<decimal> QtyPerBag { get; set; }
        public Nullable<decimal> PoRate { get; set; }
        public Nullable<decimal> JudgementQty { get; set; }
        public string JudgementMethod { get; set; }
        public string JudgeBy { get; set; }
        public Nullable<System.DateTime> JudgeOn { get; set; }
        public Nullable<decimal> PutawayQty { get; set; }
        public string BinRackID { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public string PutawayMethod { get; set; }
        public string PutBy { get; set; }
        public Nullable<System.DateTime> PutOn { get; set; }
    }
}
