//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vShelfLifeExtension
    {
        public string RMCode { get; set; }
        public string RMName { get; set; }
        public System.DateTime InDate { get; set; }
        public string LotNo { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string Extension { get; set; }
        public string Remark { get; set; }
        public string ShelfLifeBaseOnCOA { get; set; }
        public string Note { get; set; }
    }
}
