//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStockFifo
    {
        public string ID { get; set; }
        public string MaterialID { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string Barcode { get; set; }
        public string LotNumber { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal QtyPerBag { get; set; }
        public Nullable<decimal> BagQty { get; set; }
        public string Type { get; set; }
        public System.DateTime ReceivedAt { get; set; }
        public string BinRackID { get; set; }
        public Nullable<bool> QCInspected { get; set; }
        public string BinRackCode { get; set; }
        public string BinRackName { get; set; }
        public string BinRackAreaID { get; set; }
        public string BinRackAreaCode { get; set; }
        public string BinRackAreaName { get; set; }
        public string BinRackAreaType { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseType { get; set; }
    }
}
