//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStockWarehouse
    {
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string Type { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public decimal QtyPerBag { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<int> TotalBagQty { get; set; }
    }
}
