//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStockOpname
    {
        public string ID { get; set; }
        public string BinRackCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public string LotNo { get; set; }
        public System.DateTime InDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public int BagQty { get; set; }
        public string QtyPerBag { get; set; }
        public string TotalQty { get; set; }
        public string MaterialType { get; set; }
        public string ScannedBy { get; set; }
        public System.DateTime ScannedOn { get; set; }
    }
}
