//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStockRM
    {
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public decimal Qty { get; set; }
        public string UoM { get; set; }
        public string ShelfLife { get; set; }
        public decimal OrderedQty { get; set; }
        public string TransportingMode { get; set; }
        public string MinPurchaseQty { get; set; }
        public decimal Origin { get; set; }
        public string Maker { get; set; }
        public string Vendor { get; set; }
        public bool Msds { get; set; }
        public string PoRate { get; set; }
        public System.DateTime SpecGravity { get; set; }
        public string Factor { get; set; }
        public Nullable<System.DateTime> Online { get; set; }
        public Nullable<decimal> Hygroscopic { get; set; }
    }
}
