//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTransform
    {
        public string DocumentNo { get; set; }
        public string WHName { get; set; }
        public string SourceRMCode { get; set; }
        public string SourceRMName { get; set; }
        public decimal TransformQty { get; set; }
        public string TargetRMCode { get; set; }
        public string TargetRMName { get; set; }
        public string SourceBinRack { get; set; }
        public System.DateTime SourceInDate { get; set; }
        public System.DateTime SourceExpDate { get; set; }
        public string SourceLotNo { get; set; }
        public Nullable<decimal> SourceBag { get; set; }
        public decimal SourceFullBag { get; set; }
        public decimal SourceTotal { get; set; }
        public string PickingBy { get; set; }
        public System.DateTime PickingOn { get; set; }
        public string TargetBinRack { get; set; }
        public System.DateTime TargetInDate { get; set; }
        public System.DateTime TargetExpDate { get; set; }
        public string TargetLotNo { get; set; }
        public Nullable<decimal> TargetBag { get; set; }
        public decimal TargetFullBag { get; set; }
        public decimal TargetTotal { get; set; }
        public string PutawayBy { get; set; }
        public System.DateTime PutawayOn { get; set; }
        public string Status { get; set; }
        public string Memo { get; set; }
    }
}
