//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTransferSourceRM
    {
        public string DataSource { get; set; }
        public string ID { get; set; }
        public string Barcode { get; set; }
        public string MaterialName { get; set; }
        public string MaterialCode { get; set; }
        public string Uom { get; set; }
        public string LotNumber { get; set; }
        public string BinRackAreaID { get; set; }
        public string BinRackArea { get; set; }
        public string BinRackID { get; set; }
        public string BinRack { get; set; }
        public decimal Quantity { get; set; }
    }
}
