//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_BE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTransfer
    {
        public System.Guid ID { get; set; }
        public string TransferNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string MaterialCodeSource { get; set; }
        public string MaterialNameSource { get; set; }
        public string BinRackAreaNameSource { get; set; }
        public string BinRackNameSource { get; set; }
        public decimal Qty { get; set; }
        public string MaterialCodeTarget { get; set; }
        public string MaterialNameTarget { get; set; }
        public string BinRackAreaNameTarget { get; set; }
        public string BinRackNameTarget { get; set; }
        public decimal QtyTransfer { get; set; }
    }
}
